<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ClickerTycoon.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClickerTycoon.Domain\ClickerTycoon.Domain.csproj" />
    <ProjectReference Include="..\ClickerTycoon.Application\ClickerTycoon.Application.csproj" />
    <ProjectReference Include="..\ClickerTycoon.Infrastructure\ClickerTycoon.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="gameconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
